"""update user

Revision ID: 58e973ce6b4d
Revises: 2b2a0e4fa855
Create Date: 2024-07-20 01:59:36.330298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e973ce6b4d'
down_revision: Union[str, None] = '2b2a0e4fa855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_banned')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
