version: '3.8'
services:

  postgresql:
    container_name: db
    image: postgres:15.0-alpine
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  backend:
    container_name: app
    build: 
      context: .
    restart: always
    entrypoint: ["sh", "infra/run.sh"]
    depends_on:
      - postgresql
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always

  celery:
    container_name: celery
    build:
      context: .
    restart: always
    command: celery -A app.tasks.celery:celery worker -l INFO
    depends_on:
      - redis
    env_file:
      - .env

  # flower:
  #   container_name: flower
  #   build:
  #     context: .
  #   restart: on-failure
  #   command: celery -A app.tasks.celery:celery flower -l INFO
  #   depends_on:
  #     - celery
  #   env_file:
  #     - .env

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf
      - ./infra/custom_404.html:/usr/share/nginx/html/custom_404.html
    depends_on:
      - backend
    ports:
      - 80:80

volumes:
  dbdata:
