version: '3.8'

services:
  postgresql:
    container_name: db
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - 5432:5432


volumes:
  dbdata: