user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events { 
    worker_connections  1024;
}

http {
    server {
        listen                  80 default_server;
        server_name             solved-task.ru www.solved-task.ru;
        server_tokens           off;
        
        location / {
            return 404;
        }
    }
    server {
        listen                  80;
        server_name             api.solved-task.ru www.api.solved-task.ru;
        server_tokens           off;

        location / {
            proxy_pass          http://backend:8000/;
        }
        location /admin {
            return 301          http://api.solved-task.ru/;
        }
    }
    server {
        listen 80;
        server_name             85.193.88.10;
        return 301              http://solved-task.ru$request_uri;
    }
    server {
        listen                  80;
        server_name             admin.solved-task.ru www.admin.solved-task.ru;
        server_tokens           off;

        location / {
            return 301          /admin;
        }

        location /admin {
            proxy_set_header    Host $host;
            proxy_set_header    X-Forwarded-Host $host;
            proxy_set_header    X-Forwarded-Server $host;

            proxy_pass          http://backend:8000/admin;
        }

        location /admin/statics/ {
            proxy_pass          http://backend:8000/admin/statics/;
        }
    }
}